apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging
resources:
  - syslog-server-namespace.yml
  - syslog-server-pvc.yml
  - syslog-server-configmap.yml
  - syslog-server-deployment.yml
  - syslog-server-service.yml

