apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner
resources:
  - nfs-provisioner-namespace.yml
  - nfs-provisioner-rbac.yml
  - nfs-provisioner-deployment.yml
  - nfs-provisioner-storageclass.yml
