apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

resources:
  - pihole-namespace.yml
  - pihole-configmap.yml
  - pihole-pvc.yml
  - pihole-deployment.yml
  - pihole-service.yml
  - pihole-ingress.yml

