# apps/portainer/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - portainer-namespace.yml
  - portainer-rbac.yml
  - portainer-deployment.yml
  - portainer-service.yml
