apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra-namespace/infra-namespace.yml
  - dhcpd/dhcpd-app.yml
  - pxe-http/pxe-http-app.yml
  - coredns/coredns-app.yml
  - portainer/portainer-app.yml
  - nfs-provisioner/nfs-provisioner-app.yml
  - syslog-server/syslog-server-app.yml
  - log-archiver/log-archiver-app.yml
  # - influxdb/influxdb-app.yml

